stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: production

#Build Stage
build_app:
  stage: build
  image: node:20
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building project..."
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

#run stage
run_tests:
  stage: test
  image: node:20
  script:
    - echo "Running tests..."
    - npm test
  only:
    - main
    - merge_requests

#Deploy Stage
deploy_app:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying application..."
    - echo "Simulating deploy to server"
  only:
    - tags